travis:
  secure:
    BINSTAR_TOKEN: K5uAJeEErHvsl3XnI+V5XzTwlZCfvHFRHdi742tLFrLeGG8jS9e9wj/qi3V/GN+N+f2QWwMwLEXauVDwpayCxd5Iz5aRNA1kSbwR4gDjU01AQbR/JNsEALYRrQXOJvC3KVy5E4WmVx+YbeofoP2EjLkI6s59JzKgEuGbWRW54dZ+EqONkPIqWKDkgaSSBRh54GByMTtLgMEvexZW+p8kBQg6Aff79coooeO46HWrZjgXjvBxAHkLL3rCNEvAHKg1C0qivf1aKCV7Qg0z1Bl79AGp5BlZlFps+FvhmdsYPCwi12NibfRxFVFAqsFE6N4/7wQb7TITKpW7jh2Yht/DmgYEzIG9wKIN0vsfGu7ZWz8zszc8NPPVZBX4mKjUuumznL0iHrbCNEjerTo7iYYGeT71Yo6Gj76nkY7tc2SWXEKQuIkQqPps6ro7MaZB1xXA6AESKSMpw/JMEklkFFKs1ihNWPV0jqLlD4LJPWgNTjCEh9kXTq3+hNCUucv6U965CI/yLXKP8J2FDTQYzCU0I6EV4YcqkVH7rdl/5wje+0AOrQXBHcEAgbpV4zguFxNjFK1MY+IJoZvhPAyrlpcDVismoZq/6C8cVeUoXB8bVBvwGlQp2DleD6+igHDvZeGpuslYFqoDmZRRJ83yUvZApu5nzUprABMD+294CX5DZa8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
